name: Run Python script

on:
  schedule:
    - cron: '40 8 * * 1-5'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Configure Git
      run: |
        git config --global user.name 'ko-hoon'
        git config --global user.email 'seunghoon_jeon@kolon.com'

    - name: Run Python script
      env:
        KOREA_BANK_API_KEY: ${{ secrets.KOREA_BANK_API_KEY }}
        LME_PRICE_URL: ${{ secrets.LME_PRICE_URL }}
        OPINET_API_KEY: ${{ secrets.OPINET_API_KEY }}
        PUBLIC_DATA_CENTER_API_KEY: ${{ secrets.PUBLIC_DATA_CENTER_API_KEY }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: python main.py

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "test 입니다."
        git push