name: gh-pages

on:
  workflow_dispatch: # 수동 트리거
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.22.0'  # 사용할 Flutter 버전 설정

      - name: Install dependencies
        run: flutter pub get

      - name: Build web application
        run: flutter build web

      - name: Deploy to GitHub Pages
        uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /price-monitoring-flutter/
          publish_dir: ./build/web
